-- Week 2 Quiz: Chapter 3 - Kafka Producers
-- Run this in Supabase SQL Editor (Dashboard > SQL Editor)

INSERT INTO quizzes (week_number, title, description, questions)
VALUES (
  2,
  'Chapter 3: Kafka Producers',
  'Writing Messages to Kafka - Test your knowledge of producer configuration, send methods, serialization, and partitioning.',
  '[
    {
      "q": "What are the three mandatory properties when constructing a KafkaProducer?",
      "options": [
        "bootstrap.servers, key.serializer, value.serializer",
        "bootstrap.servers, acks, retries",
        "broker.list, key.serializer, value.serializer",
        "zookeeper.connect, key.serializer, value.serializer"
      ],
      "answer": 0,
      "explanation": "A Kafka producer requires bootstrap.servers (broker addresses), key.serializer, and value.serializer. All other configuration parameters have defaults."
    },
    {
      "q": "Which of the following is NOT one of the three primary methods of sending messages with a Kafka producer?",
      "options": [
        "Fire-and-forget",
        "Synchronous send",
        "Asynchronous send",
        "Transactional send"
      ],
      "answer": 3,
      "explanation": "The three methods described in Chapter 3 are fire-and-forget, synchronous send, and asynchronous send. Transactional send is not discussed as one of the primary methods."
    },
    {
      "q": "What is a disadvantage of sending messages synchronously with the Kafka producer?",
      "options": [
        "You cannot detect errors when sending messages",
        "Messages may arrive out of order",
        "It significantly reduces throughput because the producer blocks on each message",
        "It requires implementing the Callback interface"
      ],
      "answer": 2,
      "explanation": "Synchronous sending uses Future.get() to block until the broker responds. If the network roundtrip is 10ms, you can only send ~100 messages per second. The advantage is simplicity and immediate error detection, but the throughput cost is significant."
    },
    {
      "q": "What does the acks=0 configuration mean for the producer?",
      "options": [
        "The producer waits for all in-sync replicas to acknowledge",
        "The producer waits for the leader to acknowledge",
        "The producer does not wait for any acknowledgment from the broker",
        "The producer retries until at least one replica acknowledges"
      ],
      "answer": 2,
      "explanation": "With acks=0, the producer will not wait for a reply from the broker. Messages can be lost if the broker is down, but throughput is maximized."
    },
    {
      "q": "What object does the broker return when a message is successfully written to Kafka?",
      "options": [
        "ProducerRecord",
        "RecordMetadata",
        "ConsumerRecord",
        "TopicPartition"
      ],
      "answer": 1,
      "explanation": "On success, the broker returns a RecordMetadata object containing the topic, partition, and offset of the record."
    },
    {
      "q": "What happens when a message key is null and the default partitioner is used?",
      "options": [
        "The message is rejected with an error",
        "The message is always sent to partition 0",
        "The message is sent to a random partition using round-robin",
        "The message key is auto-generated by the broker"
      ],
      "answer": 2,
      "explanation": "When the key is null, the default partitioner distributes records among available partitions using a round-robin algorithm to balance messages."
    },
    {
      "q": "Why does the book recommend using Apache Avro over custom serializers for Kafka?",
      "options": [
        "Avro is faster than any custom serializer",
        "Avro schemas can evolve without breaking compatibility between readers and writers",
        "Avro is the only serialization format Kafka supports",
        "Custom serializers are not allowed in production"
      ],
      "answer": 1,
      "explanation": "Avro''s key advantage is schema evolution — you can change the schema (e.g., add/remove fields) and old/new applications continue to work without breaking, unlike custom serializers which are fragile to change."
    },
    {
      "q": "What is the role of the Schema Registry when using Avro with Kafka?",
      "options": [
        "It validates that messages don''t exceed max.request.size",
        "It stores schemas so producers and consumers can serialize/deserialize records without embedding the full schema in each message",
        "It automatically creates topics for new schemas",
        "It converts Avro records to JSON before sending"
      ],
      "answer": 1,
      "explanation": "The Schema Registry stores all schemas used to write data. The producer stores the schema identifier in the record, and consumers pull the schema from the registry to deserialize. This avoids doubling record size by embedding schemas."
    },
    {
      "q": "Is the Schema Registry part of Apache Kafka?",
      "options": [
        "Yes, it is a core component bundled with Apache Kafka",
        "No, it is a separate open source component not part of Apache Kafka",
        "Yes, but only in Kafka versions 0.9.0.0 and later",
        "No, it is a proprietary closed-source tool"
      ],
      "answer": 1,
      "explanation": "The Schema Registry is not part of Apache Kafka. It is a separate open source project (e.g., Confluent Schema Registry). There are several options to choose from, but they must be installed independently alongside Kafka."
    },
    {
      "q": "What is the main advantage of sending messages asynchronously with callbacks?",
      "options": [
        "It guarantees messages are never lost",
        "It allows high throughput while still being notified of errors when they occur",
        "It ensures messages are written to all replicas before returning",
        "It eliminates the need for serializers"
      ],
      "answer": 1,
      "explanation": "Asynchronous sending with callbacks lets you send messages without blocking (high throughput), while the callback''s onCompletion() method notifies you of failures so you can handle errors. This balances throughput and reliability — unlike fire-and-forget (no error feedback) or synchronous (blocks on every message)."
    }
  ]'::jsonb
);
